# Generated by Django 2.2.24 on 2022-01-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.ImageField(default=0, upload_to='')),
                ('quantite', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
