# Generated by Django 2.2.24 on 2022-01-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produit',
        ),
    ]
