# Generated by Django 2.2.24 on 2022-01-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220121_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.IntegerField(default=0),
        ),
    ]
