# Generated by Django 2.2.24 on 2022-01-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220121_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
