# Generated by Django 2.2.24 on 2022-01-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220121_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('produits', models.TextField()),
                ('total_vente', models.FloatField()),
                ('total_achat', models.FloatField()),
                ('total_benefice', models.FloatField()),
            ],
        ),
    ]
