# Generated by Django 2.2.24 on 2022-01-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
