# Generated by Django 2.2.24 on 2022-01-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220121_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='numero',
            field=models.CharField(max_length=16),
        ),
    ]
