# Generated by Django 2.2.24 on 2022-01-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220121_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('produits_vendus', models.FloatField()),
                ('total_vente', models.FloatField()),
                ('total_achat', models.FloatField()),
                ('total_benefice', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.DateField(),
        ),
    ]
