# Generated by Django 2.2.24 on 2022-01-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220121_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='produits_vendus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='total_achat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='total_benefice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='total_vente',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
