# Generated by Django 2.2.24 on 2022-01-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220121_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='produits_vendus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
