# Generated by Django 2.2.24 on 2022-01-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_equipe_paiement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipe',
            options={'verbose_name_plural': 'Equipe'},
        ),
    ]
